# ---- Build Stage ----
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o loadbalancer ./cmd/loadbalancer

# ---- Run Stage ----
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/loadbalancer .
COPY --from=builder /app/configs ./configs
EXPOSE 8082
CMD ["./loadbalancer"]