# ---- Build Stage ----
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o proxy ./cmd/proxy

# ---- Run Stage ----
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/proxy .
COPY --from=builder /app/configs ./configs
COPY cert.pem key.pem ./
EXPOSE 8443
CMD ["./proxy"]