server {
    listen 80;

    location /health {
        default_type application/json;
        return 200 '{"status":"healthy","service":"orders-service"}';
    }

    location /orders {
        default_type application/json;
        return 200 '{"service":"orders-service","orders":[{"id":1,"product":"Laptop","qty":1},{"id":2,"product":"Phone","qty":2}]}';
    }

    location / {
        default_type application/json;
        return 200 '{"service":"orders-service","status":"running"}';
    }
}